# General Settings
name: Bruno Moreira
job_title: Lead Software Engineer
email: brubom@gmail.com
description: I'm experienced in managing teams or working on solo projects with a high degree of complexity and delivering quality, using Scrum and XP. Strong track record of simplifying what is difficult and delivering results. I thrive in autonomous and creative environments, building a culture of fun, candor, and a bias for action.
avatar: https://s3-us-west-1.amazonaws.com/uifaces.brubom/avatar.png
favicon: /favicon.ico
twitter_handler: brubom
analytics_code: UA-111792578-1
disqus: https-brubom-github-io

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'http://twitter.com/brubom' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/brunomoreira' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/brubom' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: '' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: "true"

# Serving
url: ""
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title.html
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed